### ISSUE TITLE
SSE enabled in boot but never used

### ISSUE THREAD

**Issue by 4e554c4c** [ESALP/ESALP-1#1]
In `src/arch/x86_64/boot.asm` SSE is enabled due to lack of cross-compilation early in the project. Many modern kernels, including Linux do not use SSE or floating point instructions in kernel because they end up slowing down things and make everything more complicated. Rust uses SSE to optimize, so cross-compiling with SSE disabled maybe should be changed; but then kernel interrupts handlers will have to be more complex. Eventually there will be a userland and the SSE instructions will be used, but they are not at the moment which creates unnessisary code at boot. Should this code be purged from the project, or will it be useful later?

**Comment by jjgarzella** [comment]
there are two frames of thought: 
a) we don't care about speed right now, it's not one of our stated goals and we don't need to worry about it unless we have problems
b) we don't want unnecessary code just floating around, and if we do need it we'll know exactly how to add it, so take it away for now.
Which attitude do we want to adopt? I'm leaning toward b, because a comes from the "speed doesn't matter" and "memory is pretty much free" attitude that I get from my app programming experience, but I feel like those ideas don't exactly apply to something this low level

**Comment by 4e554c4c** [comment]
I'm not entirely sure because it sort of hinges on a design desision of the kernel: To keep the rust features such as optomising sse and floating point or not. Right now I have the x86_64-unknown-none-gnu target use **absolutely none** of those exceptions. This means that when creating an exception handler we don't need to save the sse registers (512 bytes of them!) every time we cach an exception and hand off control to rust code.
However, even if we do this I think that we should still give our *programs* full access to the sse registers. If we do this in the userland and not in the kernel we still don't have to save registers but we gain optomizations too. Technically, we could compile everything under `src/arch` with a certain target, but idk how to do that atm. We will still have to think about this when we implement processes (if we do) but I think it's a good trade off for now.

Tell me what you think about this, and close it if you'd like.

**Comment by jjgarzella** [comment]
Alright, so it seems like our conclusion is to not use SSE in the kernel, but once we get to userland, we'll put it in there. We might change this decision later.
