### ISSUE TITLE
Physical frame allocator leaks frames

### ISSUE THREAD

**Issue by 4e554c4c** [ESALP/ESALP-1#8]
So far this has not been a problem, but it needs to be solved eventually. A solution may be to use a simple bitmap that represents the locations of physical frames and whether they are used or not, there is a free frame right before the kernel that can be used for this easily.

**Comment by 4e554c4c** [comment]
Solution: Use singly linked lisk of free frames as a stack. This will be set up at boot using the existing physical frame management code (as it can give all of the availible frames incrimentally). This will create a _unused_frames_ * 16 byte overhead which does not matter at all because as physical memory fills up the overhead will go down. 
Needed to complete: a strong heap using the frame alocator to store the very large linked list

**Comment by jjgarzella** [comment]
Here's an idea that I had, what do you think: Instead of keeping a list of free frames, it keeps a list of allocated frames/addresses. When the allocator runs, it checks to see if the next frame index is taken, and if not it skips it. When the allocator gets to the end of memory, it wraps to the beginning. I say this because the existing allocator essentially does this exact thing right now, just with the taken addresses hard coded in.

**Comment by 4e554c4c** [comment]
That would be a lot less efficient. We would have to keep a bitmap of all of the physical frames in the system and then constantly seach it which would take forever. Yeah, this takes up some time at boot, but it's well worth it. The free frame stack method would take `struct_size * free_mem / page_size`, the bitmap method would take `total_mem / page_size * 8`. Also there's no real way to keep track of used memory other then this because it can be freed at any time, physical frames don't have to be used in any order at all, and they are completely process independant.
